---
#######
- name: PHASE 1-1 AWS AND CLOUDFLARE SETUP

  hosts: localhost
  roles:
    - role: p11_setup_aws_cf
      tags: [ operational, recovery ]

  vars_prompt:
    - name: target
      prompt: Provide the target account (primary/test/fallback)
      private: no


#######
- name: PHASE 1-1 WAIT FOR EC2 READINESS

  hosts: ec2
  tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:
      tags: [ operational, recovery ]


#######
- name: PHASE 1-2 WEB TIER SETUP

  hosts: web
  roles:
    - role: p12_setup_web
      tags: [ operational, recovery ]


#######
- name: PHASE 1-3 APPLICATION TIER SETUP

  hosts: app
  roles:
    - role: p13_setup_app
      tags: [ operational, recovery ]


#######
- name: PHASE 1-4 DATABASE TIER SETUP

  hosts: db
  roles:
    - role: p14_setup_db
      tags: [ operational, recovery ]


#######
- name: PHASE 1-5 SEARCH TIER SETUP

  hosts: search
  roles:
    - role: p15_setup_search
      tags: [ operational, recovery ]


#######
- name: PHASE 1-6 INTEGRATION

  hosts: app
  roles:
    - role: p16_integrate
      tags: [ operational, recovery ]


#######
- name: PHASE 2-1 STOP WEB SERVER

  hosts: web
  roles:
    - role: p21_stop_web
      tags: recovery


#######
- name: PHASE 2-2 STOP APPLICATION SERVER

  hosts: app
  roles:
    - role: p22_stop_app
      tags: recovery


#######
- name: PHASE 2-3 RESTORE DATABASE DATA

  hosts: db
  roles:
    - role: p23_restore_db
      tags: recovery


#######
- name: PHASE 2-4 RESTORE APPLICATION DATA

  hosts: app
  roles:
    - role: p24_restore_app
      tags: recovery


#######
- name: PHASE 2-5 START WEB SERVER

  hosts: app
  roles:
    - role: p25_start_app
      tags: recovery


#######
- name: PHASE 2-6 START APPLICATION SERVER

  hosts: web
  roles:
    - role: p26_start_web
      tags: recovery
