- name: Download and install the Elastic public signing key
  shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Copy Elasticsearch repo configuration
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: 0644

- name: Install the latest version of Elasticsearch from the repo
  yum:
    name: elasticsearch
    enablerepo: elasticsearch
    state: present

- name: Copy Elasticsearch configuration
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660

- name: Install required analysis-icu plugin
  shell: /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu

- name: Install required analysis-kuromoji plugin
  shell: /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-kuromoji

- name: Install required analysis-smartcn plugin
  shell: /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-smartcn

- name: Install required analysis-stempel plugin
  shell: /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-stempel

- name: Daemon reload
  systemd:
    daemon_reload: yes

- name: Start the Elasticsearch service
  systemd:
    name: elasticsearch
    state: started
    enabled: yes

